### ISSUE TITLE
gl context version on linux

### ISSUE THREAD

**Issue by monolifed** [erkkah/tigr#12]
Examples don't work.
As a workaround I used `MESA_GL_VERSION_OVERRIDE=3.3 ./demo`

**Comment by erkkah** [comment]
Hi, thanks. Yes, this is a known issue when using the Mesa drivers.

**Comment by monolifed** [comment]
Ok. There seems to be something wrong on mesa's side.
`ogl version 3.0 Mesa 18.3.6
shader compile error : 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES`

glXCreateContextAttribsARB might make it work?

**Comment by erkkah** [comment]
I'll look into it!

**Comment by erkkah** [comment]
I did a quick fix that seems to work for me ^^^. Check it out if you want, @monolifed.

**Comment by monolifed** [comment]
Nice, works for me too.

**Comment by erkkah** [comment]
Great, thanks for the help!
