### ISSUE TITLE
Android suggestion

### ISSUE THREAD

**Issue by r-lyeh** [erkkah/tigr#22]
Hey, I forgot to tell you about this. Maybe you can extract some ideas from this repo and make a pure C solution for Android too, so you merge Android support back into tigr/master. 
https://github.com/cnlohr/rawdrawandroid

**Comment by erkkah** [comment]
Hi. Thanks, I'll take a look. 
Is there anything special from that solution that you find is missing in the timogr thing?

**Comment by r-lyeh** [comment]
Not sure. I'm not familiar with Android at all. Just wanted to share :D

**Comment by erkkah** [comment]
Cool, thanks!
