### ISSUE TITLE
Changing FPS

### ISSUE THREAD

**Issue by BenStigsen** [erkkah/tigr#33]
After having spent some time with it, I have to say that I really love the simplicity and size of it. I was wondering though, is it possible to change the FPS limit?

**Comment by erkkah** [comment]
Hi there. Yes, that's what I liked about it as well when I found it some years ago.
Changing FPS is platform dependent, and would be hard to expose in a platform independent way.
Is there a specific platform you are thinking of?

**Comment by BenStigsen** [comment]
I'm using Linux.
And as far as I can tell, after having looked at the source code, VSync is enabled which is probably what's limiting the FPS.

**Comment by erkkah** [comment]
Yep. I wanted to keep the library easy to use without hogging the CPU, so I set up some form of sync or rate limiting on all platforms.
