### ISSUE TITLE
Fullscreen on windows

### ISSUE THREAD

**Issue by vchizhov** [erkkah/tigr#34]
Hi. Whenever I try to use the fullscreen mode TIGR_FULLSCREEN on windows, it seems like part of the screen is cutoff when I use the maximum resolution. I realized this while trying to blit an image. Instead if I use TIGR_AUTO | TIGR_FULLSCREEN everything is fine but the resolution used is smaller than the actual resolution of my screen. I am not quite sure what the issues is, but it seems like there's some scaling factor that TIGR applies which is off.

**Comment by erkkah** [comment]
Hi there.

When you use the "maximum resolution" - could it be that you are using the screen resolution, but the display scaling is set to a non 100% value? For example, if scaling is set to 300%, then the buffer presented to the app is 1/3 of the screen resolution.

Do you use any of the scale flags? It is possible to create a tigr window with cropped content by not setting TIGR_AUTO and setting a high scale factor.

If you haven't already, use the "flags" example to check modes and the current tigr buffer size.

**Comment by vchizhov** [comment]
You were right, it was the scale and layout in windows being set to 125%. It reduced the resolution of the app from 1920x1080 to 1536x864 with TIGR_FULLSCREEN | TIGR_AUTO, while it still allowed a window with 1920x1080 to be created when using TIGR_FULLSCREEN | TIGR_FIXED, but it was getting cut off when presented on screen. So the rescaling was coming from windows.

**Comment by erkkah** [comment]
Good to know. Thanks for reporting back!
