### ISSUE TITLE
How To Change Font Size

### ISSUE THREAD

**Issue by BenStigsen** [erkkah/tigr#35]
This might just be me not having looked into the source enough, although it feels like I have multiple times. I'm wondering how to print text (e.g. the default font) at a bigger size on screen. Do I have to modify the glyph size or what would I do to increase it? Or can I temporarily modify the scale of what I draw?

**Comment by erkkah** [comment]
Sorry for the late reply.
Yes, you will have to use a different font.
I would recommend playing with tigrfont to convert bdf fonts of different sizes to tigr fonts.

**Comment by JettMonstersGoBoom** [comment]
take a look at https://github.com/JettMonstersGoBoom/tigr 
and the fontscaled project in the examples folder.

**Comment by BenStigsen** [comment]
Yes, exactly, something like that (but only with one scale value, not x and y). 
The destination and source bitmap should probably accessed directly though, but your repo shows the feature I'm talking about.
