### ISSUE TITLE
Additional Blitting Features

### ISSUE THREAD

**Issue by rxi** [erkkah/tigr#4]
Would you be open to accepting a pull request adding additional features? I appreciate this is a fork with a specific goal such that I understand this might not be desirable.

I was thinking that in place of the `tigrBlitTint` a `tigrBlit2` or `tigrBlitAdvanced` function could be added. This would work similar to `tigrBlitTint` with the addition of two more parameters:
* A colour value that is "added" to the RGB channels of all pixels
* A bitmask with the options to draw the sprite flipped on either its X or Y axis

I feel these two features would greatly benefit the use case of the library for small games without adding much weight.

In addition to this I believe the embedded font might work better without the drop shadow -- the same effect is trivial to achieve by drawing the text twice in different colours with a 1 pixel offset, but the inverse, removing the baked-in drop shadow, is less trivial.

**Comment by Nullious** [comment]
I'd agree with tigrBlitAdvanced / tigrBlitEx 
the current font system is pretty inflexible . try editing the current font.png or loading a new font via the api. ( it would crash a lot for me ). 

I took a simpler approach and read in a font from an image into the current font / glyph structures to continue using tigrPrint api.
To be fair I don't think there should even be a font implementation as part of the library though it is very handy to have.

**Comment by rxi** [comment]
In the mean time I've made the changes I mentioned on my [fork](https://github.com/rxi/tigr). Let me know if you would like me to submit this as a pull request.
