### ISSUE TITLE
Have Tigr-nim now :)

### ISSUE THREAD

**Issue by Angluca** [erkkah/tigr#47]
Hope more people can use tigr lib :)
https://github.com/Angluca/tigr-nim

Can tigrFont generate support '中文' fonts (>=15MB .ttf) ?
I haven't tried and installed go-lang, So ask you first .

**Comment by erkkah** [comment]
Hi that's awesome!

Even though text in Tigr is UTF-8, font rendering only supports 7-bit ascii and codepage 1252.

It would be absolutely possible to add support for other bitmap font variants, but that would require updates to both Tigr and tigrFont. Would it make sense to look at something like GB 2312 ?

**Comment by Angluca** [comment]
Yes, We use GB ttf, Hopefully can be generated and used them in the future ( gb2312 or gbk all ok : )
GB2312 = 7000+ chars
GBK = 21000+ chars
GB18030 = 27000+ chars

**Comment by erkkah** [comment]
Hey, @Angluca, I've done some work on this, and have pushed something that works on my end to https://github.com/erkkah/tigrfont/tree/unicode and https://github.com/erkkah/tigr/tree/unicodefonts.

The CI test now produces this:

![](https://raw.githubusercontent.com/erkkah/tigr/unicodefonts/ci/reference.png)

It would be cool if you had time to test before I release.

**Comment by Angluca** [comment]
So awesome!

**Comment by Angluca** [comment]
```c
zsh: segmentation fault ...
```
I 've generate quan.png
![quan](https://user-images.githubusercontent.com/156404/236142778-9775ec88-92fa-4637-a1d2-b9aec0e3e44c.png)

**Comment by Angluca** [comment]
```bash
zsh: segmentation fault  ./hello
# null pointer error
```
![Screenshot2023-05-04 16 03 40](https://user-images.githubusercontent.com/156404/236145561-6980e912-4721-4c13-abc3-7c1411f3c3d4.png)

**Comment by erkkah** [comment]
Thanks a lot for testing, will take a look.
