### ISSUE TITLE
Question: Where stores the window state

### ISSUE THREAD

**Issue by milen-prg** [erkkah/tigr#52]
I use tigr under Windows 10 Pro 64 bit.
Please, say, where the tigr stores the Widow last position and state (is maximized) between the exe restarts?

**Comment by erkkah** [comment]
Hi. The window position is stored in the registry under `HKEY_CURRENT_USER/Software/TIGR/<window title>`. 
You can disable this by defining `TIGR_DO_NOT_PRESERVE_WINDOW_POSITION`.
I've thought about making that the default, since it's a bit odd for all TIGR-based apps to share window positions.

**Comment by milen-prg** [comment]
Thanks, this is very useful and good feature!
I want to use this thread to ask one more question - have some option for Anti-aliasing?

**Comment by erkkah** [comment]
No, that's out of scope for tigr primitives.
You can do whatever you want directly in the bitmap though.
Also, you could do post-filtering using a custom shader, check the shader example.
