### ISSUE TITLE
Problem with custom font

### ISSUE THREAD

**Issue by milen-prg** [erkkah/tigr#53]
I apologize, I'm not very good with the system part of the programming, but now I start with this simple graphics library and I want to use cyrillic font. I make such with:

windows>tigrfont -mx -size 20 -encoding utf8 JuliaMono-Bold.ttf JuliaMono-Bold.png
Generated unicode font sheet for 1537 characters from encoding "utf8"

I can show the result png file - it seems ok with all necessary alphabets:

![JuliaMono-Bold](https://github.com/erkkah/tigr/assets/59639866/1235d74d-6bf0-47fe-aea2-76683e94ef7a)

After that I use the slightly modified base example:

`
#include <stdio.h>
#include "tigr.h"

int main(int argc, char *argv[])
{
    Tigr *screen = tigrWindow(320, 240, "Hello", TIGR_FIXED);

    Tigr* fontImage = tigrLoadImage("../JuliaMono-Bold.png");
    TigrFont * font = tigrLoadFont(fontImage, TCP_UTF32);

    while (!tigrClosed(screen)){
        tigrClear(screen, tigrRGB(0x80, 0x90, 0xa0));
        tigrPrint(screen, font, 120, 110, tigrRGB(0xff, 0xff, 0xff), "Проба");
        tigrUpdate(screen);
    }

    tigrFree(screen);
    // tigrFreeFont(font);
    tigrFree(fontImage);

    return 0;
}
`

IMPORTANT notes:

1. I comment the line:
// tigrPrint(screen, font, 120, 110, tigrRGB(0xff, 0xff, 0xff), "Hello, world.");

and after the window closing, just before the program stops - it crashes.

2. If I comment also this line:
tigrFreeFont(font);

There is no crashes, but all works ok.

3. If I try to start the all example as is shown above - application crashes immediately. I see that the font pointer is NULL, so just for try:

- I edit (comment two rows) the library source tigr.c - row 1831:
- 
`TigrFont* tigrLoadFont(Tigr* bitmap, int codepage) {
    TigrFont* font = (TigrFont*)calloc(1, sizeof(TigrFont));
    font->bitmap = bitmap;
    if (!tigrLoadGlyphs(font, codepage)) {
        //tigrFreeFont(font);
        //return NULL;
    }
    return font;
}`

I just comment unsuccessful font return - and IT WORKS! The cyrillic word appears perfect on the window!

But:
if I did not also comment the row tigrFreeFont(font);, it crashes at closing.

I know that this is not decision, there are memory leaks, etc., but I'm not ready to inspect the library more, please for help from the author. Thanks, in advance!!!

P.S. I try the example in the /ci folder of the tigr library source - it also crashes immediately with this message in the console:
Create offscreen...OK
Drawing API... 
So I think, that the problem is somewhere in the tigr.c source. Please for support.

P.P.S I make experiments on Windows 10 Pro 64 bit with MINGW64 gcc and with MSVC 2022, the results are the same.

**Comment by erkkah** [comment]
Thanks for the detailed report. I'll look into it.
