### ISSUE TITLE
Screen size don't match on linux?

### ISSUE THREAD

**Issue by Its-Kenta** [erkkah/tigr#55]
Hi,

I've tried out Tigr on Linux (X11 KDE) and for some reason the screen size for the window doesn't seem to match with what the executable outputs?

From my understanding e.g. demo is 320x240, however. As seen on the screenshot this does not seem to be the case and the window dimensions are much bigger.

![Screenshot_20230701_211808](https://github.com/erkkah/tigr/assets/106167071/4245207d-9040-4ab4-84da-6c0345060cd5)

I'm running this and tested all tests from source.

**Comment by erkkah** [comment]
Hi there.

The size given is actually the size of the bitmap. Tigr then scales the bitmap in integer steps, as you can see when resizing the window.

This makes it easy to code small apps without having to handle different screen sizes.

Hope this helps.

**Comment by Its-Kenta** [comment]
Hi, yes sorry that actually help and found the cause of this.
Apologies for the silly issue!
